//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int Product_ID { get; set; }
        [Required]
        public string Product_Name { get; set; }
        [Required]
        [StringLength(3, ErrorMessage = "Quantity must be less than 3 digit.")]
        public string Product_Qnty { get; set; }

    }
}
