//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Purchase
    {
        public int Product_ID { get; set; }
        [Required(ErrorMessage = "Product name is required.")]
        [Display(Name = "Purchased product")]
        public string Purchase_Product { get; set; }
        [Required(ErrorMessage = "Product quantity is required.")]
        [Display(Name = "Purchased Quantity")]
        public string Purchase_Qnty { get; set; }
        [Display(Name = "Purchased Date")]
        public string Purchase_Date { get; set; }
    }
}
