//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sale
    {
        public int Product_ID { get; set; }
        [Required(ErrorMessage = "Product name is required.")]
        public string Sale_Product { get; set; }
        [Required(ErrorMessage = "Product quantity is required.")]
        public string Sale_Qnty { get; set; }
        public string Sale_Date { get; set; }
    }
}
